version: '3'
services:
  django:
    build:
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    volumes:
    - ./data:/usr/local-library/data
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
    - 8000:80
    depends_on:
      - django
