# Generated by Django 2.2.7 on 2019-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("catalog", "0002_auto_20191113_1657")]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        )
    ]
